default: &default
  adapter: mysql2
  encoding: utf8
  charset: utf8
  collation: utf8_unicode_ci
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: react_rails_sample_dev
  username: root

test:
  <<: *default
  database: react_rails_sample_test
  username: root
